### ISSUE TITLE
Support Net::LibIDN2?

### ISSUE THREAD

**Issue by ryandesign** [noxxi/p5-io-socket-ssl#106]
I see that IO::Socket::SSL uses Net::LibIDN. Has any thought been given to perhaps using Net::LibIDN2 instead, or offering the choice of whether to use Net::LibIDN or Net::LibIDN2?

**Comment by noxxi** [comment]
IO::Socket::SSL already supports URI, Net::IDN::Encode, Net::LibIDN as libraries for IDNA handling. Given that Net::LibIDN was not updated since 2009, Net::IDN::Encode since 2018 I would consider these as more or less obsolete/stable. URI is recent though and well supported and handles the necessary functionality without depending on other libraries. So this is the first choice.

Based on this I would see it more as a burden to add yet another optional IDNA dependency, especially since Net::LibIDN2 itself also depends on libidn2. It does not add enough value given the range of options already supported, notably URI.
