### ISSUE TITLE
Prompt user to re-install Net::SSLeay

### ISSUE THREAD

**Issue by davidcantrell-bb** [noxxi/p5-io-socket-ssl#133]
Trying to install the latest IO::Socket::SSL today I got this from cpanm:

```
...
Checking if you have Net::SSLeay 1.46 ... Yes (1.92)
...
Configuring IO-Socket-SSL-2.083
Running Makefile.PL
API-different OpenSSL versions compiled in (0x30000010) vs linked (0x30100000) at Makefile.PL line 68.
...
```

I fixed it by re-building Net::SSLeay, after reading Makefile.PL to see what that actually meant and where the values were coming from. It might be a good idea to be a bit more verbose and suggest that fix to the user.

**Comment by noxxi** [comment]
This means that your Net::SSLeay was compiled with OpenSSL 3.0.1 (0x30000010) while the dynamic OpenSSL library loaded was from OpenSSL 3.1.0 (0x30100000) - see also [OPENSSL_VERSION_NUMBER](https://www.openssl.org/docs/man3.0/man3/OPENSSL_VERSION_NUMBER.html). Since this is a difference in major versions the APIs are not compatible and thus problems are likely to happen.

> It might be a good idea to be a bit more verbose and suggest that fix to the user.

This indicates that something is messed up on the users system. The reasons for this might vary, like broken system, wrong LD_LIBRARY_PATH, wrong PERLLIB, ... . It is impossible to suggest the right solution without knowing the exact cause of the problem - thus only the problem itself gets reported.

If this issue happens often enough I might add more information to the error message. Right now it seems to happen only rarely though (this was the first time it was reported to me).

**Comment by davidcantrell-bb** [comment]
I think it just means that I upgraded OpenSSL at some point after building Net::SSLeay

**Comment by noxxi** [comment]
> I think it just means that I upgraded OpenSSL at some point after building Net::SSLeay

This might have been the cause have been in your case, but like I said there can be various reasons for this error.
